services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ticketVault'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
    volumes:
      - './docker/CREATE_DB.sql:/docker-entrypoint-initdb.d/1_CREATE.sql'
      - './docker/INSERT.sql:/docker-entrypoint-initdb.d/2_INSERT.sql'